Repository BadwaterBay/github-label-manager-plus, pull requests merged in 2020-05, with the labels that each got.

#10 Update README.md. Added badges of CodeFactor and GPL
  README.md
Labels: PR: review needed

#11 Created LICENSE file (GPLv3)
  LICENSE
Labels: PR: review accepted

#13 Replace all 'var' instances with 'let' in app.js
  js/app.js
Labels: PR: review needed, PR: test needed, complexity: 1

#17 Upgrade Bootstrap & jQuery and make necessary adjustments
  css/app.css
  css/bootstrap-responsive.css
  css/bootstrap.css
  index.html
  js/app.js
  js/bootstrap.bundle.js
  js/bootstrap.js
  js/jquery.js
Labels: PR: review needed, complexity: 3, lang: css, lang: html, lang: javascript, type: enhancement

#22 Fixes #15: Debug: allow copying more than 28 labels at a time by recursion
  js/app.js
Labels: PR: review accepted

#25 Fixes #24: Updated link of fork me on github
  index.html
Labels: PR: review needed

#26 Fixes #4: Debug/enable commit button after copying labels from other repos
  js/app.js
Labels: PR: review needed

#28 Add 'Delete all labels' button and allow committing after
  index.html
  js/app.js
Labels: PR: review needed, complexity: 2, lang: html, lang: javascript, type: feature request

#30 Remove all defined but unused variables within app.js
  js/app.js
Labels: PR: review needed, complexity: 1, lang: javascript, type: enhancement, type: maintenance

#31 Update all '==' to '===' in app.js
  js/app.js
Labels: PR: review needed, complexity: 1, lang: javascript, type: enhancement

#33 Merge declarations of duplicate selectors
  css/colorpicker.css
Labels: PR: review needed, complexity: 1, lang: css, type: maintenance

#38 Fix #37: Clean up cosmetic stuff and fix typos/errors in html and js
  index.html
  js/app.js
Labels: PR: revision needed

#41 Feature: Streamline removing all existing labels and cloning from another repo; UI touch-ups.
  css/app.css
  index.html
  js/app.js
Labels: PR: review needed, lang: css, lang: html, lang: javascript, type: feature request

#44 Rewrote copy-all-labels algorithm
  js/app.js
Labels: PR: review accepted

#45 Fix #42:Remove confirm popup really want to delete this
  js/app.js
Labels: PR: review accepted

#46 Fix #6: Changed from 3-column design to 2-column design
  index.html
Labels: PR: review accepted

#48 Fix #2: New feature: add label description
  css/app.css
  index.html
  js/app.js
Labels: PR: review needed

#47 Feature: Enable recovery button and share functionality across 'deleteAllButton' and 'cloneFromRepoButton' + minor CSS updates
  js/app.js
Labels: PR: review needed, complexity: 3, lang: css, lang: html, lang: javascript, type: bug, type: feature request

#51 Pop up alert when there are 0 existing labels
  js/app.js
Labels: PR: review needed, lang: javascript, type: feature request

#53 Fix 52: Replace bootstrap w/ material design for bootstrap
  index.html
  js/app.js
Labels: PR: review accepted

#56 Fix #55 Improve input form UI. Split own:repo input to separate inputs
  index.html
  js/app.js
Labels: PR: review accepted

#58 Fix #57: Add "I'm owner of repo" checkbox and auto-copy owner to username if checked
  index.html
  js/app.js
Labels: PR: review accepted

#59 Revise delete behavior to grey out; UI tweaks
  css/app.css
  js/app.js
Labels: PR: review needed, lang: css, lang: javascript, type: enhancement

#62 Fix 61: Move How-works & Access-token cards after Labels card
  index.html
Labels: PR: review accepted

#63 Employ SCSS as CSS pre-processor
  css/app.css
  css/app.min.css
  css/app.min.css.map
  index.html
  scss/app.scss
Labels: PR: review needed, lang: css, lang: html, type: enhancement

#67 Fix #66: Check label's description when setting action attribute
  js/app.js
Labels: PR: review accepted

#69 Place entries in cards and adapt layout/buttons
  css/app.min.css
  css/app.min.css.map
  index.html
  js/app.js
  scss/app.scss
Labels: PR: review needed, complexity: 3, lang: css, lang: javascript, type: enhancement

#70 Fix #27: Feature/add manage milestone
  css/app.min.css.map
  index.html
  js/app.js
Labels: PR: review accepted

#74 Fix #72 & #73 Bugfix update, delete & commit milestones and labels
  js/app.js
Labels: PR: review accepted

#77 Fix #75 Housekeeping: remove legacy & commented-out code & files
  css/app.min.css
  css/app.min.css.map
  css/bootstrap.css
  img/glyphicons-halflings-white.png
  img/glyphicons-halflings.png
  index.html
  js/app.js
  js/bootstrap.bundle.js
  js/jquery.js
  scss/app.scss
Labels: PR: review accepted

#80 Adjust column layout and breakpoint
  css/app.min.css
  css/app.min.css.map
  index.html
  scss/app.scss
Labels: complexity: 2/5, lang: html, status: review needed, type: enhancement

#83 Bugfix enable commit after copy labels/milestones from other repo
  js/app.js
Labels: status: review accepted

#85 Fix #84 Debug: commit/create milestones copied from other repo
  js/app.js
Labels: status: review accepted

#86 Simplify jQuery .parent() chaining
  css/app.min.css
  css/app.min.css.map
  js/app.js
  scss/app.scss
Labels: complexity: 2/5, lang: css, lang: javascript, status: review needed, type: enhancement

#88 Substitute jQuery .parents() for .closest()
  js/app.js
Labels: lang: javascript, status: review needed, type: maintenance

#89 Employ tab layout for labels, milestones & FAQ
  css/app.min.css
  css/app.min.css.map
  index.html
  js/app.js
  scss/app.scss
Labels: lang: css, lang: html, lang: javascript, status: review needed

#92 Fix #35 Replace ambiguous icon with save button to save color
  css/colorpicker.css
  js/colorpicker.js
Labels: status: review needed

#95 Fix milestone update not adding 'uncommitted'
  js/app.js
Labels: lang: javascript, status: review needed

#98 Fix #78: Remove 2 unnecessary semicolons
  js/app.js
Labels: status: review accepted

#100 Fix #99: Simplify delete-all-and-copy-button mechanism
  js/app.js
Labels: status: review accepted

#96 Fix saving color adding extra uncommitted class to parent element
  js/app.js
Labels: lang: javascript, status: review needed

#104 Use .blur() in place of .change() for monitoring input changes
  js/app.js
Labels: lang: javascript, status: review needed, type: bug

#103 Disable 'revert' buttons until user modifies entries
  index.html
  js/app.js
Labels: complexity: 3/5, lang: html, lang: javascript, status: review needed, type: enhancement

#108 Fix #107 Initialize npm and add eslint
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
Labels: status: revision needed

#110 Fix #91 & #65 Add function query login info & fix username
  index.html
  js/app.js
Labels: status: review accepted

#113 Change 'labels' to singular form in commit modal messages
  js/app.js
Labels: lang: javascript, status: review needed, type: enhancement

#111 Maintenance: Fix ESLint errors
  js/app.js
  js/colorpicker.js
Labels: lang: javascript, status: revision needed, type: maintenance

#118 Updated README
  README.md
Labels: status: review accepted

#120 Fix #115 Check for duplicate label names and milestone titles
  css/app.min.css
  css/app.min.css.map
  js/app.js
  scss/app.scss
Labels: status: review accepted

#122 Add Prettier to package.json & workflow
  .eslintrc.json
  .github/pull_request_template.md
  .prettierignore
  README.md
  css/colorpicker.css
  index.html
  js/colorpicker.js
  package-lock.json
  package.json
  scss/app.scss
Labels: status: review needed

#123 Infrastructure: minor updates on readme, workflow, package.json
  .github/pull_request_template.md
  README.md
  package.json
Labels: status: review accepted

#124 Add editable milestone due-date and status fields
  js/app.js
Labels: complexity: 4/5, lang: javascript, status: review needed, type: feature request

#125 Rename 'action' attribute to '(data)-todo'
  js/app.js
Labels: lang: javascript, status: review needed, type: maintenance

#129 Housekeep: Change let&func to const, use arrow, update precommit hook
  .eslintignore
  .eslintrc.js
  .eslintrc.json
  .prettierignore
  .prettierrc.js
  README.md
  index.html
  js/app.js
  js/colorpicker.js
  package-lock.json
  package.json
  scss/app.scss
Labels: status: revision needed

#131 Fix #130 Bugfix: update, delete, then commit a label fails
  js/app.js
Labels: status: review needed

#133 Fix #132 Fix Eslint no-invalid-this errors by add JSDoc
  .eslintrc.js
  js/app.js
Labels: status: review accepted

#135 Make input changes monitor all other inputs to determine 'todo'
  js/app.js
Labels: lang: javascript, status: review needed, type: bug
