Repository BadwaterBay/github-label-manager-plus, pull requests merged in 2020-06, with the labels that each got.

#138 Fix #126 Tweak UI & buttons & remove buttons for simplicity
  .eslintignore
  css/app.min.css
  css/app.min.css.map
  index.html
  js/app.js
  package.json
  scss/app.scss
Labels: status: review accepted, type: enhancement

#140 Update organization name and link in all relevant files
  README.md
  index.html
  package.json
Labels: status: review accepted

#142 Typo fixes and other minor text updates
  README.md
  index.html
Labels: status: review accepted

#143 Set up grid for label inputs; validate/auto-style color inputs
  css/app.min.css
  css/app.min.css.map
  js/app.js
  scss/app.scss
Labels: lang: css, lang: javascript, status: review needed, type: enhancement, type: feature request

#144 Relocate web app to ./src dir & update lint & format rules
  package.json
  src/css/app.min.css
  src/css/app.min.css.map
  src/css/colorpicker.css
  src/images/blank.gif
  src/images/colorpicker_background.png
  src/images/colorpicker_hex.png
  src/images/colorpicker_hsb_b.png
  src/images/colorpicker_hsb_h.png
  src/images/colorpicker_hsb_s.png
  src/images/colorpicker_indic.gif
  src/images/colorpicker_overlay.png
  src/images/colorpicker_rgb_b.png
  src/images/colorpicker_rgb_g.png
  src/images/colorpicker_rgb_r.png
  src/images/colorpicker_select.gif
  src/images/colorpicker_submit.png
  src/images/custom_background.png
  src/images/custom_hex.png
  src/images/custom_hsb_b.png
  src/images/custom_hsb_h.png
  src/images/custom_hsb_s.png
  src/images/custom_indic.gif
  src/images/custom_rgb_b.png
  src/images/custom_rgb_g.png
  src/images/custom_rgb_r.png
  src/images/custom_submit.png
  src/images/select.png
  src/images/select2.png
  src/images/slider.png
  src/index.html
  src/js/app.js
  src/js/colorpicker.js
  src/scss/app.scss
Labels: status: review accepted

#145 Fix #146 Arrange html to js components and add webpack
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/components/copyFromCard.js
  src/components/dashboardCard.js
  src/components/loadingModal.js
  src/components/loginCard.js
  src/components/managementCard.js
  src/components/navbar.js
  src/index.html
  src/index.js
  src/js/app.js
  webpack.config.js
Labels: status: review accepted

#147 Let new entry additions check for 'todo'
  src/js/app.js
Labels: lang: javascript, status: review needed, type: bug

#148 Validate required fields before API calls
  src/css/app.min.css
  src/css/app.min.css.map
  src/js/app.js
  src/scss/app.scss
Labels: lang: css, lang: javascript, status: review needed, type: enhancement, type: feature request

#149 Update new project name and update README text
  README.md
  package-lock.json
  package.json
  src/components/navbar.js
  src/index.html
Labels: status: review needed

#151 Add feature to close modal by clicking outside
  src/components/loadingModal.js
  src/js/app.js
Labels: lang: javascript, status: review needed, type: enhancement

#156 Check duplicates on commit; keyup to remove warning
  src/css/app.min.css
  src/css/app.min.css.map
  src/js/app.js
  src/scss/app.scss
Labels: complexity: 4/5, lang: javascript, status: review needed, type: enhancement, type: feature request

#161 Minor updates on README: add link
  README.md
Labels: status: review needed

#168 Fix 169: Upgrade dependencies & switch to yarn
  .eslintignore
  .eslintrc.js
  .github/workflows/nodejs.yml
  .gitignore
  .prettierignore
  .prettierrc.js
  README.md
  bs-config.js
  package-lock.json
  package.json
  src/css/app.min.css.map
  src/index.html
  src/index.js
  src/js/app.js
  src/js/colorpicker.js
  src/scss/app.scss
  webpack.config.js
  yarn.lock
Labels: status: review needed
